// Email Service
// Sends screening result emails via Gmail SMTP using Nodemailer

require('dotenv').config();
const nodemailer = require('nodemailer');

// Create reusable transporter using Gmail SMTP
const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS      // Gmail App Password (16 chars)
    }
});

/**
 * Sends a resume screening result email to the candidate
 * @param {string} toEmail - Candidate's email address
 * @param {string} candidateName - Candidate's name
 * @param {string} jobTitle - Job they applied for
 * @param {Object} screeningResult - The AI-generated screening result object
 */
async function sendScreeningResultEmail(toEmail, candidateName, jobTitle, screeningResult) {
    const { matchScore, verdict, summary, strengths, weaknesses, skills, recommendation } = screeningResult;

    // Build strengths/weakness HTML lists
    const strengthsList = (strengths || []).map(s => `<li>✅ ${s}</li>`).join('');
    const weaknessesList = (weaknesses || []).map(w => `<li>❌ ${w}</li>`).join('');
    const matchedSkills = (skills?.matched || []).map(s => `<span class="skill matched">${s}</span>`).join(' ');
    const missingSkills = (skills?.missing || []).map(s => `<span class="skill missing">${s}</span>`).join(' ');

    // Color based on score
    const scoreColor = matchScore >= 75 ? '#22c55e' : matchScore >= 50 ? '#f59e0b' : '#ef4444';

    const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body { font-family: 'Segoe UI', Arial, sans-serif; background: #f1f5f9; margin: 0; padding: 20px; }
    .container { max-width: 620px; margin: auto; background: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 24px rgba(0,0,0,0.08); }
    .header { background: linear-gradient(135deg, #1e293b, #334155); padding: 32px; text-align: center; }
    .header h1 { color: #ffffff; margin: 0; font-size: 22px; }
    .header p { color: #94a3b8; margin: 6px 0 0; font-size: 14px; }
    .score-box { text-align: center; padding: 28px; background: #f8fafc; border-bottom: 1px solid #e2e8f0; }
    .score-circle { display: inline-block; width: 90px; height: 90px; border-radius: 50%; background: ${scoreColor}; color: white; font-size: 28px; font-weight: 800; line-height: 90px; }
    .verdict { display: inline-block; margin: 12px 0 0; padding: 6px 18px; border-radius: 20px; background: ${scoreColor}20; color: ${scoreColor}; font-weight: 700; font-size: 14px; }
    .body { padding: 28px 32px; }
    .section { margin-bottom: 24px; }
    .section h3 { color: #1e293b; font-size: 15px; margin: 0 0 10px; padding-bottom: 6px; border-bottom: 2px solid #e2e8f0; }
    .section p { color: #475569; font-size: 14px; line-height: 1.6; margin: 0; }
    ul { margin: 0; padding-left: 18px; color: #475569; font-size: 14px; line-height: 1.8; }
    .skill { display: inline-block; padding: 3px 10px; border-radius: 12px; font-size: 12px; margin: 3px; }
    .matched { background: #dcfce7; color: #16a34a; }
    .missing { background: #fee2e2; color: #dc2626; }
    .recommendation-box { background: #f0f9ff; border-left: 4px solid #0ea5e9; padding: 14px 16px; border-radius: 4px; }
    .recommendation-box p { color: #0369a1; font-size: 14px; margin: 0; }
    .footer { text-align: center; padding: 20px; background: #f8fafc; color: #94a3b8; font-size: 12px; border-top: 1px solid #e2e8f0; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>🤖 AI Resume Screening Result</h1>
      <p>Application Review for: <strong style="color:#e2e8f0">${jobTitle}</strong></p>
    </div>

    <div class="score-box">
      <p style="color:#64748b; margin:0 0 12px; font-size:14px">Hello <strong>${candidateName}</strong>, here is your application result:</p>
      <div class="score-circle">${matchScore}%</div>
      <br>
      <span class="verdict">${verdict}</span>
    </div>

    <div class="body">
      <div class="section">
        <h3>📋 Summary</h3>
        <p>${summary}</p>
      </div>

      <div class="section">
        <h3>💪 Strengths</h3>
        <ul>${strengthsList}</ul>
      </div>

      <div class="section">
        <h3>⚠️ Areas for Improvement</h3>
        <ul>${weaknessesList}</ul>
      </div>

      <div class="section">
        <h3>🛠️ Skills</h3>
        <p><strong>Matched:</strong> ${matchedSkills || 'N/A'}</p>
        <p style="margin-top:8px"><strong>Missing:</strong> ${missingSkills || 'N/A'}</p>
      </div>

      <div class="section">
        <h3>🎯 Final Recommendation</h3>
        <div class="recommendation-box">
          <p>${recommendation}</p>
        </div>
      </div>
    </div>

    <div class="footer">
      This analysis was generated by AI and is meant to assist with screening. © AI Resume Screener
    </div>
  </div>
</body>
</html>
`;

    const mailOptions = {
        from: process.env.EMAIL_FROM,
        to: toEmail,
        subject: `Your Application Result - ${jobTitle} | AI Resume Screener`,
        html: htmlContent
    };

    const info = await transporter.sendMail(mailOptions);
    console.log(`✅ Email sent to ${toEmail} | Message ID: ${info.messageId}`);
    return info;
}

/**
 * Verify the email transporter is working
 */
async function verifyEmailConnection() {
    try {
        await transporter.verify();
        console.log('✅ Gmail SMTP connection verified');
        return true;
    } catch (error) {
        console.error('❌ Gmail SMTP verification failed:', error.message);
        return false;
    }
}

module.exports = { sendScreeningResultEmail, verifyEmailConnection };
